mkdir BatchData
mkdir BatchData\Numerical
mkdir BatchData\Candlestick
mkdir RealTimeData
mkdir RealTimeData\Numerical
mkdir RealTimeData\Candlestick
mkdir RealTimeResults
mkdir yolo
mkdir yolo\weights